# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_auto_20180325_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binID', models.IntegerField()),
                ('geoLocation', models.TextField(default='None', max_length=420)),
                ('description', models.TextField(default='None', max_length=420)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
