# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binID', models.IntegerField()),
                ('geoLocation', models.TextField(max_length=420)),
                ('binStatus', models.IntegerField()),
            ],
        ),
    ]
