# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='lastPickUpTime',
            field=models.TextField(default='None', max_length=420),
        ),
        migrations.AddField(
            model_name='bin',
            name='requestUrgent',
            field=models.IntegerField(default=0),
        ),
    ]
